name: random_commit_message
description: A simple app that uses whatthecommit.com to fetch and display random commit messages

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.8
  web_scraper: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
